#Application Config
spring.application.name=cart-service
logging.level.root=DEBUG
server.port=8082
server.servlet.context-path=/cart-service
#Database
spring.data.mongodb.uri=mongodb://localhost:27017/cartdb
#Internal Client
product.service.base-url=http://localhost:8081/product-catalog/
