version: '3.8'

services:
  nxt-uauth-service:
    image: nxt-uauth-service:latest
    container_name: uauth-service-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/uauth_db
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: 3lBNpuebl0

    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 3lBNpuebl0
      POSTGRES_DB: uauth_db
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: